-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 17:49:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BankSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BankSystem` ;

-- -----------------------------------------------------
-- Schema BankSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BankSystem` DEFAULT CHARACTER SET utf8 ;
USE `BankSystem` ;

-- -----------------------------------------------------
-- Table `BankSystem`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Phone` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Phone` (
  `idPhone` INT NOT NULL AUTO_INCREMENT,
  `phoneType` VARCHAR(30) NOT NULL,
  `phoneNumber` INT NOT NULL,
  PRIMARY KEY (`idPhone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Country` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `countryName` VARCHAR(40) NOT NULL,
  `localCurrency` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`City` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `cityName` VARCHAR(80) NOT NULL,
  `localIndicative` VARCHAR(5) NULL,
  `latitude` INT NULL,
  `longitude` INT NULL,
  `idCountry` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fkCity_Country_idx` (`idCountry` ASC) VISIBLE,
  CONSTRAINT `fkCity_Country`
    FOREIGN KEY (`idCountry`)
    REFERENCES `BankSystem`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`AccountType` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`AccountType` (
  `idTypeAccount` INT NOT NULL AUTO_INCREMENT,
  `typeAccountName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTypeAccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Account` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `avalibility` TINYINT NOT NULL,
  `accountName` VARCHAR(50) NOT NULL,
  `accountNumber` INT NOT NULL,
  `avalibleBalance` INT NOT NULL DEFAULT 0,
  `minBalance` INT NOT NULL,
  `totalBalance` INT NOT NULL DEFAULT 0,
  `expirationDate` DATETIME NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updateAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `idTypeAccount` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `fkAccount_TypeAccount_idx` (`idTypeAccount` ASC) VISIBLE,
  CONSTRAINT `fkAccount_TypeAccount`
    FOREIGN KEY (`idTypeAccount`)
    REFERENCES `BankSystem`.`AccountType` (`idTypeAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Goal` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Goal` (
  `idGoal` INT NOT NULL AUTO_INCREMENT,
  `goalName` VARCHAR(80) NOT NULL,
  `goalDescription` VARCHAR(200) NULL,
  `finalDate` DATETIME NOT NULL,
  `goalAmount` INT NOT NULL,
  `goalState` TINYINT(1) NOT NULL DEFAULT 1,
  `goalBalance` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idGoal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Saving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Saving` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Saving` (
  `idSaving` INT NOT NULL AUTO_INCREMENT,
  `savingName` VARCHAR(50) NOT NULL,
  `savingBalance` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idSaving`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Pocket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Pocket` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Pocket` (
  `idPocket` INT NOT NULL AUTO_INCREMENT,
  `pocketName` VARCHAR(50) NOT NULL,
  `pocketBalance` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPocket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Portafolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Portafolio` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Portafolio` (
  `idPortafolio` INT NOT NULL AUTO_INCREMENT,
  `handlingFee` INT NULL,
  `idAccount` INT NOT NULL,
  `idSaving` INT NOT NULL,
  `idPocket` INT NOT NULL,
  `idGoal` INT NOT NULL,
  PRIMARY KEY (`idPortafolio`),
  INDEX `fk_Portafolio_Account_idx` (`idAccount` ASC) VISIBLE,
  INDEX `fk_Portafolio_Goal_idx` (`idGoal` ASC) VISIBLE,
  INDEX `fk_Portafolio_Saving_idx` (`idSaving` ASC) VISIBLE,
  INDEX `fk_Portafolio_Pocket_idx` (`idPocket` ASC) VISIBLE,
  CONSTRAINT `fk_Portafolio_Account`
    FOREIGN KEY (`idAccount`)
    REFERENCES `BankSystem`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Portafolio_Goal`
    FOREIGN KEY (`idGoal`)
    REFERENCES `BankSystem`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Portafolio_Saving`
    FOREIGN KEY (`idSaving`)
    REFERENCES `BankSystem`.`Saving` (`idSaving`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Portafolio_Pocket`
    FOREIGN KEY (`idPocket`)
    REFERENCES `BankSystem`.`Pocket` (`idPocket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`User` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(70) NULL,
  `lastName` VARCHAR(70) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `gender` ENUM('M', 'F', 'ND') NOT NULL,
  `birthdate` DATETIME NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `idPhone` INT NOT NULL,
  `idCity` INT NOT NULL,
  `idPortafolio` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fkUserPhone_idx` (`idPhone` ASC) VISIBLE,
  INDEX `fkUserCity_idx` (`idCity` ASC) VISIBLE,
  INDEX `fkUser_Portafolio_idx` (`idPortafolio` ASC) VISIBLE,
  CONSTRAINT `fkUserPhone`
    FOREIGN KEY (`idPhone`)
    REFERENCES `BankSystem`.`Phone` (`idPhone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkUserCity`
    FOREIGN KEY (`idCity`)
    REFERENCES `BankSystem`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkUser_Portafolio`
    FOREIGN KEY (`idPortafolio`)
    REFERENCES `BankSystem`.`Portafolio` (`idPortafolio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`TransactionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`TransactionType` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`TransactionType` (
  `idTransactionType` INT NOT NULL AUTO_INCREMENT,
  `transactionTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransactionType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`TransactionStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`TransactionStatus` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`TransactionStatus` (
  `idTransactionStatus` INT NOT NULL AUTO_INCREMENT,
  `transactionStatusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransactionStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Taxe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Taxe` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Taxe` (
  `idTaxe` INT NOT NULL AUTO_INCREMENT,
  `taxeName` VARCHAR(50) NOT NULL,
  `percentage` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idTaxe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BankSystem`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BankSystem`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `BankSystem`.`Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `transactionDate` DATETIME NOT NULL,
  `transactioAmount` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `idTransactionType` INT NOT NULL,
  `idTransactionStatus` INT NOT NULL,
  `idTaxe` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `fkTransaction_TransactionType_idx` (`idTransactionType` ASC) VISIBLE,
  INDEX `fkTransaction_TransactionStatus_idx` (`idTransactionStatus` ASC) VISIBLE,
  INDEX `fk_Transaction_Taxe_idx` (`idTaxe` ASC) VISIBLE,
  INDEX `fk_Transaction_User_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fkTransaction_TransactionType`
    FOREIGN KEY (`idTransactionType`)
    REFERENCES `BankSystem`.`TransactionType` (`idTransactionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkTransaction_TransactionStatus`
    FOREIGN KEY (`idTransactionStatus`)
    REFERENCES `BankSystem`.`TransactionStatus` (`idTransactionStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Taxe`
    FOREIGN KEY (`idTaxe`)
    REFERENCES `BankSystem`.`Taxe` (`idTaxe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `BankSystem`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

alter table user add constraint fk_user_phone foreign key (idPhone)
       references phone (idPhone) on delete restrict on update restrict;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
